name: foody
description: "Gestiona tu inventario y recetas"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.0

# ----- Packages -----
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  mongo_dart: ^0.10.5
  mailer: ^6.0.0
  google_sign_in: ^6.3.0
  flutter_stripe: ^11.5.0
  flutter_local_notifications: ^19.2.1
  permission_handler: ^12.0.0+1
  device_info_plus: ^11.4.0
  
  # ---- Utility Packages ----
  salomon_bottom_bar: ^3.3.2
  flutter_rating_bar: ^4.0.1
  lucide_icons: ^0.257.0

  # ---- Icons ----
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8

  # ---- State Management ----
  get: ^4.7.2
  http: ^1.3.0
  intl: ^0.20.2
  url_launcher: ^6.3.1
  intl_phone_field: ^3.2.0
  country_picker: ^2.0.27
  flutter_native_splash: ^2.4.5
  image_picker: ^1.1.2
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # ---- Local Assets ----
  assets:
    - assets/logos/
    - assets/images/
    - assets/icons/
    - assets/categories/
    - assets/anuncios/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
          style: normal
        - asset: assets/fonts/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
          style: normal
